export const noteList = [
  {name: "Parent Note", child: [{ name: "child note" }]},
  {name: "Parentfdfdfsdfgfdf Note2", child: [{ name: "chiasdasddld note2"}]},
  {name: "asdasdasd", child: [{ name: "child nzzzote3"}]},
  {name: "Parentfsd Note4", child: [{ name: "childasdasdasd note4"}]},
  {name: "ParentadsasasdasdasdasdasdasdasddNote5", child: [{ name: "child note5"}, { name: "aasa"}]},
  {name: "Parentaaa Note6", child: [{ name: "aasa" }] },
  {name: "Parentadsasd Note5", child: [{ name: "child note5"}, { name: "aalalalallalalalalallalalalakdlklkajsdlkajsdklasdsa"}]},
  {name: "Parentadsasd Note5", child: [{ name: "child note5"}, { name: "aasa"}]},
  {name: "Parentadsasd Note5", child: [{ name: "child note5"}, { name: "aasa"}]},
  {name: "Parentadsasd Note5", child: [{ name: "child note5"}, { name: "aasa"}]},
  {name: "Parentadsasd Note5", child: [{ name: "child note5"}, { name: "aasa"}]},
  {name: "Parentadsasd Note5", child: [{ name: "child note5"}, { name: "aasa"}]},
  {name: "Parentadsaasdsdsd Nasdasdasdasdote5", child: [{ name: "child note5"}, { name: "aasa"}]},
  {name: "Parentadsasd Note5", child: [{ name: "child note5"}, { name: "aasa"}]},
  {name: "Parentadsasd Note5", child: [{ name: "child note5"}, { name: "aasa"}]},
  {name: "Parentadsasd Note5", child: [{ name: "child note5"}, { name: "aasa"}]},
  {name: "Parentadsasd Note5", child: [{ name: "child note5"}, { name: "aasa"}]},
  {name: "Parentadsasd Note5", child: [{ name: "child note5"}, { name: "aasa"}]},
]